nome=input("Digite o seu nome: ")
idade=int(input("Digite a sua idade: "))
gestante = (input( "Você está gestante? Digite S para sim e N para não: "))
deficiencia = (input("Você possui alguma dediciência de mobilidade? Digite S para sim e N para não: "))
febre = (input("Sua temperatura é maior que 37*C? digite S para sim e N para não: "))
Dor_cabeça  = (input("Você esta sentindo dor de cabeça ício súbito ou rapidamente progressiva? digite S para sim e N para não: "))
asma = (input("Você esta em crise asmática? digite S para sim e N para não: "))
emese = (input("Você esta sentindo nauseas/ vômito? digite S para sim e N para não: "))
dor_abominal = (input("Você esta sentindo dor abdominal? digite S para sim e N para não: "))
evacuacao = (input("Você evacuou nas ultimas 24 horas? digite S para sim e N para não: "))
sangue = (input("Você houve presença de sangue nas fezes? Digite S para sim e N para não: "))
queda =(input("Você bateu a cabeça ? digite S para sim e N para não: "))
desmaio = (input("Você esta desmaiou/ perdeu a consiência? digite S para sim e N para não: "))
gestante = gestante.upper()
deficiencia = deficiencia.upper()
febre = febre.upper()
Dor_cabeça = Dor_cabeça.upper()
asma = asma.upper()
emese= emese.upper()
dor_abominal = dor_abominal.upper()
evacuacao = evacuacao.upper()
sangue = sangue.upper()
queda = queda.upper()
desmaio =desmaio.upper()

if idade>=65:
    prioridade="SIM"
print("O paciente " + nome + " possui atendimento prioritário? " + prioridade)